### PR TITLE
fixes parameter name

### PR DESCRIPTION
**Pull request by rpaskin**
I just copied and pasted your example and noticed the parameter name inconsistency, hope it helps!

### CODE REVIEW

**Comment by edisonchee** [comment]
Appreciate this a lot! Thanks for catching the error :)

**Comment by rpaskin** [comment]
Glad to help. :)

**Comment by rpaskin** [comment]
Quick question: any tips on going about this and adding webhooks or something so I could deploy a project to heroku? Thanks!

**Comment by edisonchee** [comment]
Have you looked at [Telegram's guide](https://core.telegram.org/bots/webhooks) yet? Maybe I should do up a guide for webhooks :)

**Pull request merged**
